### PR TITLE
NPE on HotRodServer start when binding to 0.0.0.0 #114

### LINKED ISSUE #114: NPE on HotRodServer start when binding to 0.0.0.0
```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-10-07 08:41:48,468 INFO  [io.quarkus] (main) infinispan-quarkus-server-runner 14.0.0.Final native (powered by Quarkus 2.13.0.Final) started in 0.008s. 
2022-10-07 08:41:48,468 INFO  [io.quarkus] (main) Profile prod activated. 
2022-10-07 08:41:48,468 INFO  [io.quarkus] (main) Installed features: [cdi, infinispan-embedded, infinispan-server]
2022-10-07 08:41:48,469 INFO  [BOOT] (main) JVM Substrate VM Oracle Corporation GraalVM 22.1.0 Java 11 CE
2022-10-07 08:41:48,469 INFO  [BOOT] (main) JVM arguments = [-Dinfinispan.server.home.path=/opt/infinispan, --bind-address=0.0.0.0]
2022-10-07 08:41:48,469 INFO  [BOOT] (main) PID = 43
2022-10-07 08:41:48,469 INFO  [org.inf.SERVER] (main) ISPN080000: Infinispan Server 14.0.0.Final starting
2022-10-07 08:41:48,469 INFO  [org.inf.SERVER] (main) ISPN080017: Server configuration: infinispan.xml
2022-10-07 08:41:48,469 INFO  [org.inf.SERVER] (main) ISPN080032: Logging configuration: /opt/infinispan/server/conf/log4j2.xml
2022-10-07 08:41:48,475 WARN  [org.inf.SERVER] (main) ISPN080059: No script engines are available
2022-10-07 08:41:48,480 INFO  [org.inf.CONTAINER] (main) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
2022-10-07 08:41:48,489 INFO  [org.inf.CLUSTER] (main) ISPN000078: Starting JGroups channel `cluster` with stack `tcp`
2022-10-07 08:41:48,494 WARN  [org.inf.rem.tra.jgr.JGroupsTransport] (main) ISPN000671: RAFT protocol is not available. Reason: transport.node-name is not set.
2022-10-07 08:41:48,494 INFO  [org.jgr.JChannel] (main) local_addr: fc999d41-26c8-434a-ab9d-9286829b5e44, name: 7a07d9475d54-64085
2022-10-07 08:41:48,495 INFO  [org.jgr.pro.FD_SOCK2] (main) server listening on *.57800
2022-10-07 08:41:50,495 INFO  [org.jgr.pro.pbc.GMS] (main) 7a07d9475d54-64085: no members discovered after 2000 ms: creating cluster as coordinator
2022-10-07 08:41:50,496 INFO  [org.inf.CLUSTER] (main) ISPN000094: Received new cluster view for channel cluster: [7a07d9475d54-64085|0] (1) [7a07d9475d54-64085]
2022-10-07 08:41:50,508 INFO  [org.inf.CLUSTER] (main) ISPN000079: Channel `cluster` local address is `7a07d9475d54-64085`, physical addresses are `[172.17.0.4:7800]`
2022-10-07 08:41:50,510 INFO  [org.inf.CONTAINER] (main) ISPN000390: Persisted state, version=14.0.0.Final timestamp=2022-10-07T08:41:50.509775Z
2022-10-07 08:41:50,532 INFO  [org.inf.CONTAINER] (main) ISPN000104: Using EmbeddedTransactionManager
2022-10-07 08:41:50,575 INFO  [org.inf.ser.cor.tel.TelemetryServiceFactory] (ForkJoinPool.commonPool-worker-5) ISPN000953: OpenTelemetry integration is disabled
2022-10-07 08:41:50,577 INFO  [org.inf.SERVER] (main) ISPN080018: Started connector Resp (internal)
2022-10-07 08:41:50,577 INFO  [org.inf.SERVER] (ForkJoinPool.commonPool-worker-5) ISPN080018: Started connector REST (internal)
2022-10-07 08:41:50,577 FATAL [org.inf.SERVER] (main) ISPN080028: Infinispan Server failed to start: java.lang.NullPointerException
	at org.infinispan.server.hotrod.MultiHomedServerAddress$InetAddressWithNetMask.<init>(MultiHomedServerAddress.java:175)
	at org.infinispan.server.hotrod.MultiHomedServerAddress.<init>(MultiHomedServerAddress.java:42)
	at org.infinispan.server.hotrod.ServerAddress.forAddress(ServerAddress.java:24)
	at org.infinispan.server.hotrod.HotRodServer.addSelfToTopologyView(HotRodServer.java:321)
	at org.infinispan.server.hotrod.HotRodServer.startInternal(HotRodServer.java:267)
	at org.infinispan.server.core.AbstractProtocolServer.start(AbstractProtocolServer.java:118)
	at org.infinispan.server.SecurityActions.lambda$startProtocolServer$3(SecurityActions.java:88)
	at org.infinispan.security.Security.doPrivileged(Security.java:56)
	at org.infinispan.server.SecurityActions.doPrivileged(SecurityActions.java:40)
	at org.infinispan.server.SecurityActions.startProtocolServer(SecurityActions.java:87)
	at org.infinispan.server.Server.lambda$run$3(Server.java:445)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)

2022-10-07 08:41:50,579 INFO  [org.inf.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `cluster`
2022-10-07 08:41:50,580 INFO  [org.inf.CONTAINER] (main) ISPN000390: Persisted state, version=14.0.0.Final timestamp=2022-10-07T08:41:50.580694Z
2022-10-07 08:41:50,682 INFO  [io.quarkus] (main) infinispan-quarkus-server-runner stopped in 0.000s
```

We need to replace the `MultiHomedServerAddress#PRIVATE_NETWORKS` with an empty list to prevent the NPE.

### PR DESCRIPTION
**Pull request by ryanemerson**
Resolves #114

### CODE REVIEW

File: server/runtime/src/main/java/org/infinispan/quarkus/server/runtime/graal/FixInetAddress.java [hunk 1]
```diff
@@ -44,6 +45,6 @@ final class MultiHomedServerAddress {
    static org.infinispan.server.hotrod.MultiHomedServerAddress.InetAddressWithNetMask RFC4193_LINK_LOCAL;
 
    @Alias
-   @RecomputeFieldValue(kind = RecomputeFieldValue.Kind.Reset)
-   static List<org.infinispan.server.hotrod.MultiHomedServerAddress.InetAddressWithNetMask> PRIVATE_NETWORKS;
-}
\ No newline at end of file
+   @RecomputeFieldValue(kind = RecomputeFieldValue.Kind.FromAlias)
+   static List<org.infinispan.server.hotrod.MultiHomedServerAddress.InetAddressWithNetMask> PRIVATE_NETWORKS = Collections.emptyList();
```
Comment (wburns) [inline server/runtime/src/main/java/org/infinispan/quarkus/server/runtime/graal/FixInetAddress.java:49]: This seems fine to me. However, now that I really think about it, is it okay that all of these are null/empty?

Comment (ryanemerson) [reply server/runtime/src/main/java/org/infinispan/quarkus/server/runtime/graal/FixInetAddress.java:49]: I wondered the same. It will work for the vast of majority of users, however there was some users running customised Openshift installations who ran into problems, hence the creation of ISPN-14171.

Comment (wburns) [reply server/runtime/src/main/java/org/infinispan/quarkus/server/runtime/graal/FixInetAddress.java:49]: Hrmm, alright. I wonder if we should start a limitations page or something for the native server.

**Comment by wburns** [comment]
Integrated into main, thanks @ryanemerson !
